version: '3'

networks:
  default:
    name: nw_portal_transparencia

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:z
      - ./docker/conf/mysql/mysql-dump/:/docker-entrypoint-initdb.d/:z
    ports:
      - "3306:3306"
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=portal_transparencia_dev
      - MYSQL_PASSWORD=portal_transparencia_dev
      - MYSQL_DATABASE=portal_transparencia_dev

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=redis
    volumes:
      - ./docker/data/redis:/data:z

  php:
    build: ./docker/dockerfiles/php7.4-fpm
    container_name: php
    ports:
      - "9000"
      - "9003"
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=php
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - PHP_IDE_CONFIG=serverName=app
    volumes:
      - ./:/var/www/html/app/:z
      - ./docker/conf/hosts:/etc/hosts:z
      - ./docker/conf/locale:/etc/default/locale:z
      - ./docker/conf/php/php-dev.ini:/usr/local/etc/php/php.ini:z
      - ./docker/conf/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:z
      - ./docker/conf/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:z

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=nginx
    volumes:
      - ./:/var/www/html/app/:z
      - ./docker/conf/hosts:/etc/hosts:z
      - ./docker/conf/nginx/cert.pem:/etc/nginx/ssl/cert.pem:z
      - ./docker/conf/nginx/cert.key:/etc/nginx/ssl/cert.key:z
      - ./docker/conf/nginx/app.conf:/etc/nginx/conf.d/app.conf:z
      - ./docker/conf/nginx/empty.conf:/etc/nginx/conf.d/default.conf:z
    links:
      - php