version: '3.9'

networks:
  network:
    driver: ${NETWORKS_DRIVER?}

volumes:
  mysql:
    name: mysql-app
    driver: ${VOLUMES_DRIVER?}
  redis:
    name: redis-app
    driver: ${VOLUMES_DRIVER?}

services:
  php-base:
    image: larapi/php-base
    container_name: larapi_php_base
    build:
      context: .
      dockerfile: ./images/php/base/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}

  php-fpm:
    image: larapi/php-fpm
    container_name: larapi_php_fpm
    build:
      context: .
      dockerfile: images/php/php-fpm/Dockerfile
      args:
        - BASE_IMAGE=larapi/php-base
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - php-base

  application:
    image: larapi/application
    container_name: larapi_application
    build:
      context: .
      dockerfile: ./images/php/application/Dockerfile
      args:
        - BASE_IMAGE=larapi/php-base
        - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
    tty: true
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - php-base
      - nginx

  nginx:
    image: larapi/nginx
    container_name: larapi_nginx
    build:
      context: .
      dockerfile: ./images/nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    networks:
      network:
        aliases:
          - ${APP_HOST?}
    depends_on:
      - php-fpm

  redis:
    image: larapi/redis
    container_name: larapi_redis
    build:
      context: .
      dockerfile: ./images/redis/Dockerfile
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    command: >
      --requirepass ${REDIS_PASSWORD?}
    volumes:
      - ${REDIS_ENTRYPOINT}:/data
    networks:
      - network

  mysql:
      image: larapi/mysql
      container_name: larapi_mysql
      build:
        context: .
        dockerfile: ./images/mysql/Dockerfile
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${MYSQL_ENTRYPOINT}:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - network
